/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#e0e3e1",
        "outline": "#6e7977",
        "background": "#f7faf8",
        "on-tertiary-container": "#ffe5db",
        "tertiary-fixed-dim": "#ffb598",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#72361b",
        "tertiary-container": "#9c573a",
        "on-background": "#181c1c",
        "on-secondary-container": "#546866",
        "inverse-surface": "#2d3130",
        "surface-dim": "#d7dbd9",
        "tertiary": "#7f4025",
        "on-surface-variant": "#3e4947",
        "surface-bright": "#f7faf8",
        "surface-container": "#ebefed",
        "surface": "#f7faf8",
        "on-primary-fixed-variant": "#00504a",
        "inverse-primary": "#80d5cb",
        "tertiary-fixed": "#ffdbce",
        "surface-container-high": "#e5e9e7",
        "on-secondary-fixed": "#0b1f1d",
        "on-primary-fixed": "#00201d",
        "surface-tint": "#006a63",
        "secondary-fixed-dim": "#b5cbc8",
        "on-primary-container": "#a3faef",
        "surface-container-low": "#f1f4f3",
        "surface-variant": "#e0e3e1",
        "secondary-fixed": "#d1e7e4",
        "error": "#ba1a1a",
        "inverse-on-surface": "#eef1f0",
        "on-secondary-fixed-variant": "#374a49",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "secondary": "#4e6260",
        "primary-container": "#0f766e",
        "on-tertiary-fixed": "#370e00",
        "on-surface": "#181c1c",
        "outline-variant": "#bdc9c6",
        "error-container": "#ffdad6",
        "primary": "#005c55",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#80d5cb",
        "secondary-container": "#d1e7e4",
        "primary-fixed": "#9cf2e8",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff"
      },
      spacing: {
        "sm": "8px",
        "base": "4px",
        "lg": "24px",
        "xl": "32px",
        "md": "16px",
        "margin-mobile": "16px",
        "xs": "4px",
        "margin-desktop": "32px",
        "gutter": "24px",
        "2xl": "48px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Inter"],
        "label-md": ["Inter"],
        "body-md": ["Inter"],
        "headline-lg": ["Inter"],
        "display-lg": ["Inter"],
        "body-lg": ["Inter"],
        "headline-md": ["Inter"],
        "title-lg": ["Inter"],
        "body-sm": ["Inter"],
        "label-lg": ["Inter"]
      },
      fontSize: {
        "headline-lg-mobile": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "label-md": ["12px", {"lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "500"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "headline-lg": ["28px", {"lineHeight": "36px", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "display-lg": ["36px", {"lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "body-lg": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
        "headline-md": ["22px", {"lineHeight": "30px", "fontWeight": "600"}],
        "title-lg": ["18px", {"lineHeight": "24px", "fontWeight": "600"}],
        "body-sm": ["12px", {"lineHeight": "18px", "fontWeight": "400"}],
        "label-lg": ["14px", {"lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "500"}]
      }
    },
  },
  plugins: [],
}
